### ISSUE TITLE
Ads Assignment #1: Can't log in

### ISSUE THREAD

**Issue by ldavidr3** [csev/dj4e-samples#39]
UPDATE: 

The following issue was detected using PythonAnywhere. I managed to finish the assignment starting over in a local project and just copying the necessary code from dj4e-samples. However, it'd be interesting to understand why it isn't working in PA.

----
Hello,

When I try to log in to the ads app it says 
  ModuleNotFoundError at /accounts/login/
  No module named 'oauthlib'

I've done pip install requirements.txt AND requirements4.txt, also I've tried pip install oathlib in my virtual environment but it says i already have it (3.2.2).

I think this is weird because I could log in and log out in the previous assignments (Autos and Cats CRUD)

I'm adding the error log whole error log so you could help figure out what's happening
[error_log.txt](https://github.com/csev/dj4e-samples/files/9893686/error_log.txt)

**Comment by ldavidr3** [comment]
I also get this from the console:

(django4) 15:16 ~/django_projects $ python3 --version                                                                 
Python 3.9.13
(django4) 16:05 ~/django_projects $ python3 -m django --version
4.0.7
(django4) 16:05 ~/django_projects $ python3 -m oauth --version                                                        
/home/eeveesden/.virtualenvs/django4/bin/python3: No module named oauth.__main__; 'oauth' is a package and cannot be directly executed
(django4) 16:05 ~/django_projects $ python3 -m oauthlib --version                                                     
/home/eeveesden/.virtualenvs/django4/bin/python3: No module named oauthlib
(django4) 16:05 ~/django_projects $ pip3.6 install oauthlib                                                           
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: oauthlib in /home/eeveesden/.local/lib/python3.6/site-packages (3.2.2)


as you can see it says there's no oauthlib even though it also says the requirement is already satisfied

**Comment by csev** [comment]
We do not debug student code here in github.
