### ISSUE TITLE
Issue with "Using GitHub With Django and PythonAnywhere" 

### ISSUE THREAD

**Issue by pranabsarma18** [csev/dj4e-samples#47]
I have followed everything as mentioned in https://www.dj4e.com/assn/dj4e_github.md but while executing the following command it is throwing error as " remote: Support for password authentication was removed on August 13, 2021."

git push -u origin main
(enter id and password for git)

Here is the error screenshot:

![github_error](https://github.com/csev/dj4e-samples/assets/104676966/906c0f51-9c8b-4fb6-9766-351682dcd36b)

**Comment by srcatto** [comment]
This isn't a course issue. The course instructions stop at "(enter id and password for git)". The rest is a git issue, generated by running "git push". Open the URL returned by the GitHub command - lucky me it's still in my history from a year or more ago, 

https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls

"Git will ask for your GitHub username and password. When Git prompts you for your password, enter your personal access token.". Create a PAT.
For other info, https://support.github.com/ search for the issue "remote push personal access token", there are a couple of pages or results.

Images are fine, including the text copy/paste of the message is also handy.

**Comment by pranabsarma18** [comment]
Thanks for helping me out resolving this issue. I used Personal Access Token instead of the password and it worked.

**Comment by csev** [comment]
Cool
