### ISSUE TITLE
No manage.py file in Tracks folder

### ISSUE THREAD

**Issue by kojinki** [csev/dj4e-samples#50]
Hello Doc Charles, I found Issue during your walkthrough on Youtube in mark [5:03:xx](https://www.youtube.com/watch?v=o0XbHvKxw7Y&t=18234s), that there no manage.py files on tracks folder on dj4e-samples. If there has been an update I also cannot find update message, if there was any.

**Comment by csev** [comment]
The manage.py is in the folder above tracks.

**Comment by MarkusEicher** [comment]
I left a comment in #37
