### ISSUE TITLE
Django Data Models Quiz

### ISSUE THREAD

**Issue by pranabsarma18** [csev/dj4e-samples#52]
There are two same question in this quiz.

![image](https://github.com/csev/dj4e-samples/assets/104676966/d0e1638c-e427-4555-b32c-79170bc2ca82)

**Comment by csev** [comment]
Fixed - thanks.

**Comment by csev** [comment]
This of course is not in this repo - but I fixed both the private repo with quizzes and the www.dj4e.com web site.
