### ISSUE TITLE
Autos CRUD (Sample project) provided login details not working

### ISSUE THREAD

**Issue by wecanwork** [csev/dj4e-samples#64]
For  Autos CRUD https://samples.dj4e.com/accounts/login/?next=/autos/
on https://samples.dj4e.com/

The provided log in details don't work for me
"You might need an account and password to log in for certain features. You might try this:
Username: dj4e-samples
Password: dj4e_nn_! "

**Comment by csev** [comment]
The "nn" is "42" - this is not where you request help for the assignments.

**Comment by wecanwork** [comment]
Thank you!

Love your courses. I'm still new to this, I didn't know where else to ask.
I found the course on Youtube.

Jaco
